-- Generated by scripts/build-db.mjs from tokens/tokens.json and src/components.meta.json.
BEGIN;
INSERT INTO system (key, value) VALUES ('name', 'Didáctica Universitaria');
INSERT INTO system (key, value) VALUES ('version', '3');
INSERT INTO system (key, value) VALUES ('source', 'Manual_Didactica_Universitaria.docx (Word styles and direct formatting), revised by the v2 and v3 typography, colour and contrast audit (see README, Audit; v3 follows the design-system audit of 8 Oct 2026). Brand hues kept from the source; screen sizes raised for reading.');
INSERT INTO theme (id, name, position) VALUES ('light', 'Light', 0);
INSERT INTO theme (id, name, position) VALUES ('dark', 'Dark', 1);
INSERT INTO color_token (name, usage, position) VALUES ('navy', 'Brand navy (source). Unit titles (h1), cover title, glossary terms, table header fill in light theme. Text on `paper`, `surface` and every box surface.', 0);
INSERT INTO color_value (token, theme, value) VALUES ('navy', 'light', '#1f3864');
INSERT INTO color_value (token, theme, value) VALUES ('navy', 'dark', '#c9d6ee');
INSERT INTO color_token (name, usage, position) VALUES ('azure', 'Brand azure (source). Section and sub-section headings (h2, h3), chapter kicker, cover kicker. Text on `paper`.', 1);
INSERT INTO color_value (token, theme, value) VALUES ('azure', 'light', '#2e5496');
INSERT INTO color_value (token, theme, value) VALUES ('azure', 'dark', '#9fb8e6');
INSERT INTO color_token (name, usage, position) VALUES ('ink', 'Body copy, lists, table cells. Text on `paper`, `surface`, `band` and every box surface (≥ 13:1).', 2);
INSERT INTO color_value (token, theme, value) VALUES ('ink', 'light', '#1b1f27');
INSERT INTO color_value (token, theme, value) VALUES ('ink', 'dark', '#e6eaf2');
INSERT INTO color_token (name, usage, position) VALUES ('ink-muted', 'Secondary text: table and figure notes, cover lede, diagram captions. Text on `paper` and `surface` (≥ 7:1).', 3);
INSERT INTO color_value (token, theme, value) VALUES ('ink-muted', 'light', '#4a5363');
INSERT INTO color_value (token, theme, value) VALUES ('ink-muted', 'dark', '#b4bccb');
INSERT INTO color_token (name, usage, position) VALUES ('paper', 'Page ground.', 4);
INSERT INTO color_value (token, theme, value) VALUES ('paper', 'light', '#ffffff');
INSERT INTO color_value (token, theme, value) VALUES ('paper', 'dark', '#10151f');
INSERT INTO color_token (name, usage, position) VALUES ('surface', 'Screen backdrop behind pages; diagram node fill.', 5);
INSERT INTO color_value (token, theme, value) VALUES ('surface', 'light', '#f5f7fb');
INSERT INTO color_value (token, theme, value) VALUES ('surface', 'dark', '#161c28');
INSERT INTO color_token (name, usage, position) VALUES ('rule', 'Hairlines: table rows, running-header underline, box header divider. Decorative.', 6);
INSERT INTO color_value (token, theme, value) VALUES ('rule', 'light', '#c3cde0');
INSERT INTO color_value (token, theme, value) VALUES ('rule', 'dark', '#334059');
INSERT INTO color_token (name, usage, position) VALUES ('rule-strong', 'Lines that carry meaning: diagram connectors and arrows, table top and bottom rules (≥ 3:1 on `paper`).', 7);
INSERT INTO color_value (token, theme, value) VALUES ('rule-strong', 'light', '#6f7f99');
INSERT INTO color_value (token, theme, value) VALUES ('rule-strong', 'dark', '#7d8aa3');
INSERT INTO color_token (name, usage, position) VALUES ('table-head', 'Table header row fill. Pair with `on-table-head`.', 8);
INSERT INTO color_value (token, theme, value) VALUES ('table-head', 'light', '#1f3864');
INSERT INTO color_value (token, theme, value) VALUES ('table-head', 'dark', '#2a4a82');
INSERT INTO color_token (name, usage, position) VALUES ('on-table-head', 'Header-cell text on `table-head`; text on `diagram-node-strong`.', 9);
INSERT INTO color_value (token, theme, value) VALUES ('on-table-head', 'light', '#ffffff');
INSERT INTO color_value (token, theme, value) VALUES ('on-table-head', 'dark', '#ffffff');
INSERT INTO color_token (name, usage, position) VALUES ('band', 'Zebra fill on even table rows; row-header cells of concept tables.', 10);
INSERT INTO color_value (token, theme, value) VALUES ('band', 'light', '#f2f5fa');
INSERT INTO color_value (token, theme, value) VALUES ('band', 'dark', '#171f2e');
INSERT INTO color_token (name, usage, position) VALUES ('running', 'Running header and footer. Text on `paper` (5.6:1; the source #8090A8 was 3.2:1).', 11);
INSERT INTO color_value (token, theme, value) VALUES ('running', 'light', '#5c6a82');
INSERT INTO color_value (token, theme, value) VALUES ('running', 'dark', '#8b97ad');
INSERT INTO color_token (name, usage, position) VALUES ('link', 'Links and DOIs, underlined. Text on `paper` and box surfaces.', 12);
INSERT INTO color_value (token, theme, value) VALUES ('link', 'light', '#0b5cad');
INSERT INTO color_value (token, theme, value) VALUES ('link', 'dark', '#8ab4f8');
INSERT INTO color_token (name, usage, position) VALUES ('focus', '2px focus ring on links and controls (≥ 3:1 on `paper` and every box surface).', 13);
INSERT INTO color_value (token, theme, value) VALUES ('focus', 'light', '#b4530a');
INSERT INTO color_value (token, theme, value) VALUES ('focus', 'dark', '#f5a35c');
INSERT INTO color_token (name, usage, position) VALUES ('keypoints-accent', '“Puntos Clave” box: header band fill (title and icon in `paper` on it), bullet markers. Text on `keypoints-surface`.', 14);
INSERT INTO color_value (token, theme, value) VALUES ('keypoints-accent', 'light', '#1f3864');
INSERT INTO color_value (token, theme, value) VALUES ('keypoints-accent', 'dark', '#b9cbef');
INSERT INTO color_token (name, usage, position) VALUES ('keypoints-surface', '“Puntos Clave” box fill.', 15);
INSERT INTO color_value (token, theme, value) VALUES ('keypoints-surface', 'light', '#e8eef8');
INSERT INTO color_value (token, theme, value) VALUES ('keypoints-surface', 'dark', '#16203a');
INSERT INTO color_token (name, usage, position) VALUES ('keypoints-border', '“Puntos Clave” box frame and header divider.', 16);
INSERT INTO color_value (token, theme, value) VALUES ('keypoints-border', 'light', '#b9c7e0');
INSERT INTO color_value (token, theme, value) VALUES ('keypoints-border', 'dark', '#34497a');
INSERT INTO color_token (name, usage, position) VALUES ('objectives-accent', '“Objetivos” box: header band fill (title and icon in `paper` on it), Bloom tags. Text on `objectives-surface`.', 17);
INSERT INTO color_value (token, theme, value) VALUES ('objectives-accent', 'light', '#0d5c63');
INSERT INTO color_value (token, theme, value) VALUES ('objectives-accent', 'dark', '#8fd3cc');
INSERT INTO color_token (name, usage, position) VALUES ('objectives-surface', '“Objetivos” box fill.', 18);
INSERT INTO color_value (token, theme, value) VALUES ('objectives-surface', 'light', '#e2f1ef');
INSERT INTO color_value (token, theme, value) VALUES ('objectives-surface', 'dark', '#0f2a2b');
INSERT INTO color_token (name, usage, position) VALUES ('objectives-border', '“Objetivos” box frame, Bloom tag outline.', 19);
INSERT INTO color_value (token, theme, value) VALUES ('objectives-border', 'light', '#a8d0cd');
INSERT INTO color_value (token, theme, value) VALUES ('objectives-border', 'dark', '#275c5c');
INSERT INTO color_token (name, usage, position) VALUES ('important-accent', '“Importante” box: 4px top rule, title, icon, defined term. Text on `important-surface`.', 20);
INSERT INTO color_value (token, theme, value) VALUES ('important-accent', 'light', '#8a4b00');
INSERT INTO color_value (token, theme, value) VALUES ('important-accent', 'dark', '#f2c27a');
INSERT INTO color_token (name, usage, position) VALUES ('important-surface', '“Importante” box fill.', 21);
INSERT INTO color_value (token, theme, value) VALUES ('important-surface', 'light', '#fdf3e1');
INSERT INTO color_value (token, theme, value) VALUES ('important-surface', 'dark', '#2e220f');
INSERT INTO color_token (name, usage, position) VALUES ('important-border', '“Importante” box frame.', 22);
INSERT INTO color_value (token, theme, value) VALUES ('important-border', 'light', '#e8c58a');
INSERT INTO color_value (token, theme, value) VALUES ('important-border', 'dark', '#6b4c1c');
INSERT INTO color_token (name, usage, position) VALUES ('mistake-accent', '“Error Frecuente” box: 4px top rule, title, icon, the misconception label. Text on `mistake-surface`.', 23);
INSERT INTO color_value (token, theme, value) VALUES ('mistake-accent', 'light', '#a3271c');
INSERT INTO color_value (token, theme, value) VALUES ('mistake-accent', 'dark', '#f3a39a');
INSERT INTO color_token (name, usage, position) VALUES ('mistake-surface', '“Error Frecuente” box fill.', 24);
INSERT INTO color_value (token, theme, value) VALUES ('mistake-surface', 'light', '#fcebe8');
INSERT INTO color_value (token, theme, value) VALUES ('mistake-surface', 'dark', '#33150f');
INSERT INTO color_token (name, usage, position) VALUES ('mistake-border', '“Error Frecuente” box frame.', 25);
INSERT INTO color_value (token, theme, value) VALUES ('mistake-border', 'light', '#e9b1a9');
INSERT INTO color_value (token, theme, value) VALUES ('mistake-border', 'dark', '#7a3329');
INSERT INTO color_token (name, usage, position) VALUES ('thinking-accent', '“Para Seguir Pensando” box: title, icon, question numbers. Text on `thinking-surface`.', 26);
INSERT INTO color_value (token, theme, value) VALUES ('thinking-accent', 'light', '#5a3486');
INSERT INTO color_value (token, theme, value) VALUES ('thinking-accent', 'dark', '#cdb3ef');
INSERT INTO color_token (name, usage, position) VALUES ('thinking-surface', '“Para Seguir Pensando” box fill (closing family: no tint, frame and header rule only).', 27);
INSERT INTO color_value (token, theme, value) VALUES ('thinking-surface', 'light', '#ffffff');
INSERT INTO color_value (token, theme, value) VALUES ('thinking-surface', 'dark', '#10151f');
INSERT INTO color_token (name, usage, position) VALUES ('thinking-border', '“Para Seguir Pensando” box frame.', 28);
INSERT INTO color_value (token, theme, value) VALUES ('thinking-border', 'light', '#cdb8e4');
INSERT INTO color_value (token, theme, value) VALUES ('thinking-border', 'dark', '#503b78');
INSERT INTO color_token (name, usage, position) VALUES ('example-accent', '“En el aula” box: top rule, title, icon, discipline tag. Text on `example-surface`.', 29);
INSERT INTO color_value (token, theme, value) VALUES ('example-accent', 'light', '#8b2f62');
INSERT INTO color_value (token, theme, value) VALUES ('example-accent', 'dark', '#f0a8cf');
INSERT INTO color_token (name, usage, position) VALUES ('example-surface', '“En el aula” box fill.', 30);
INSERT INTO color_value (token, theme, value) VALUES ('example-surface', 'light', '#fbeef5');
INSERT INTO color_value (token, theme, value) VALUES ('example-surface', 'dark', '#2f1424');
INSERT INTO color_token (name, usage, position) VALUES ('example-border', '“En el aula” box frame.', 31);
INSERT INTO color_value (token, theme, value) VALUES ('example-border', 'light', '#e5b5cf');
INSERT INTO color_value (token, theme, value) VALUES ('example-border', 'dark', '#6e2f52');
INSERT INTO color_token (name, usage, position) VALUES ('selfcheck-accent', '“Autoevaluación” box: title, icon, question numbers. Text on `paper`.', 32);
INSERT INTO color_value (token, theme, value) VALUES ('selfcheck-accent', 'light', '#0f5f86');
INSERT INTO color_value (token, theme, value) VALUES ('selfcheck-accent', 'dark', '#93cdef');
INSERT INTO color_token (name, usage, position) VALUES ('selfcheck-surface', '“Autoevaluación” box fill (closing family: no tint).', 33);
INSERT INTO color_value (token, theme, value) VALUES ('selfcheck-surface', 'light', '#ffffff');
INSERT INTO color_value (token, theme, value) VALUES ('selfcheck-surface', 'dark', '#10151f');
INSERT INTO color_token (name, usage, position) VALUES ('selfcheck-border', '“Autoevaluación” box frame.', 34);
INSERT INTO color_value (token, theme, value) VALUES ('selfcheck-border', 'light', '#a9c8dc');
INSERT INTO color_value (token, theme, value) VALUES ('selfcheck-border', 'dark', '#2f5670');
INSERT INTO color_token (name, usage, position) VALUES ('activities-accent', '“Actividades” box: title, icon, task numbers and type tags. Text on `activities-surface`.', 35);
INSERT INTO color_value (token, theme, value) VALUES ('activities-accent', 'light', '#2d6a2e');
INSERT INTO color_value (token, theme, value) VALUES ('activities-accent', 'dark', '#a7d79b');
INSERT INTO color_token (name, usage, position) VALUES ('activities-surface', '“Actividades” box fill (closing family: no tint, frame and header rule only).', 36);
INSERT INTO color_value (token, theme, value) VALUES ('activities-surface', 'light', '#ffffff');
INSERT INTO color_value (token, theme, value) VALUES ('activities-surface', 'dark', '#10151f');
INSERT INTO color_token (name, usage, position) VALUES ('activities-border', '“Actividades” box frame.', 37);
INSERT INTO color_value (token, theme, value) VALUES ('activities-border', 'light', '#b3d3a8');
INSERT INTO color_value (token, theme, value) VALUES ('activities-border', 'dark', '#33603a');
INSERT INTO color_token (name, usage, position) VALUES ('references-accent', '“Referencias” box: title and icon. Text on `references-surface`.', 38);
INSERT INTO color_value (token, theme, value) VALUES ('references-accent', 'light', '#3f4b5e');
INSERT INTO color_value (token, theme, value) VALUES ('references-accent', 'dark', '#c3cbd8');
INSERT INTO color_token (name, usage, position) VALUES ('references-surface', '“Referencias” box fill (closing family: no tint, frame and header rule only).', 39);
INSERT INTO color_value (token, theme, value) VALUES ('references-surface', 'light', '#ffffff');
INSERT INTO color_value (token, theme, value) VALUES ('references-surface', 'dark', '#10151f');
INSERT INTO color_token (name, usage, position) VALUES ('references-border', '“Referencias” box frame.', 40);
INSERT INTO color_value (token, theme, value) VALUES ('references-border', 'light', '#c7ccd5');
INSERT INTO color_value (token, theme, value) VALUES ('references-border', 'dark', '#3d4655');
INSERT INTO color_token (name, usage, position) VALUES ('diagram-node', 'Diagram node fill (concept web branches, cycle and flow steps). Text `ink`.', 41);
INSERT INTO color_value (token, theme, value) VALUES ('diagram-node', 'light', '#eef2f9');
INSERT INTO color_value (token, theme, value) VALUES ('diagram-node', 'dark', '#1b2438');
INSERT INTO color_token (name, usage, position) VALUES ('diagram-node-border', 'Diagram node outline (≥ 2.5:1 on `paper`; the label carries the meaning).', 42);
INSERT INTO color_value (token, theme, value) VALUES ('diagram-node-border', 'light', '#8fa3c7');
INSERT INTO color_value (token, theme, value) VALUES ('diagram-node-border', 'dark', '#5a74a6');
INSERT INTO color_token (name, usage, position) VALUES ('diagram-node-strong', 'Central or emphasised node fill. Text `on-table-head`.', 43);
INSERT INTO color_value (token, theme, value) VALUES ('diagram-node-strong', 'light', '#1f3864');
INSERT INTO color_value (token, theme, value) VALUES ('diagram-node-strong', 'dark', '#3a5ea3');
INSERT INTO color_token (name, usage, position) VALUES ('ramp-1', 'Pyramid/level ramp, top (most advanced) level. Text `on-table-head`.', 44);
INSERT INTO color_value (token, theme, value) VALUES ('ramp-1', 'light', '#1f3864');
INSERT INTO color_value (token, theme, value) VALUES ('ramp-1', 'dark', '#3a5ea3');
INSERT INTO color_token (name, usage, position) VALUES ('ramp-2', 'Pyramid ramp, level 2. Text `on-table-head`.', 45);
INSERT INTO color_value (token, theme, value) VALUES ('ramp-2', 'light', '#2e5496');
INSERT INTO color_value (token, theme, value) VALUES ('ramp-2', 'dark', '#2e4b80');
INSERT INTO color_token (name, usage, position) VALUES ('ramp-3', 'Pyramid ramp, level 3. Text `ink`.', 46);
INSERT INTO color_value (token, theme, value) VALUES ('ramp-3', 'light', '#9fb6dc');
INSERT INTO color_value (token, theme, value) VALUES ('ramp-3', 'dark', '#24395f');
INSERT INTO color_token (name, usage, position) VALUES ('ramp-4', 'Pyramid ramp, base level. Text `ink`.', 47);
INSERT INTO color_value (token, theme, value) VALUES ('ramp-4', 'light', '#d6e0f0');
INSERT INTO color_value (token, theme, value) VALUES ('ramp-4', 'dark', '#1b2a45');
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('spacing', 'space-1', '4px', 'Table cell padding (vertical); tag padding.', 0);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('spacing', 'space-2', '8px', 'List item and h3 space after; icon–title gap; cell padding (horizontal).', 1);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('spacing', 'space-3', '12px', 'Paragraph space after; box header padding; h2 space after.', 2);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('spacing', 'space-4', '16px', 'Box body padding; h1 space after; gap between diagram nodes.', 3);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('spacing', 'space-5', '24px', 'Space around boxes, tables and figures; h3 space before.', 4);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('spacing', 'space-6', '32px', 'h1 and h2 space before.', 5);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('spacing', 'space-8', '48px', 'Chapter opener padding; space between chapters.', 6);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('spacing', 'indent-bullet', '24px', 'Bullet position (0.25in); list text starts at `indent-hang`.', 7);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('spacing', 'indent-hang', '48px', 'French (hanging) indent of references and block-quote indent (0.5in, APA 7).', 8);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('spacing', 'page-margin', '96px', 'Page margins (1in) on wide screens and print.', 9);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('spacing', 'measure', '680px', 'Width of wide elements: boxes, tables and figures (680px).', 10);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('spacing', 'measure-text', '31rem', 'Running-text width (496px ≈ 66 characters of 16px Cambria/Caladea, measured; Bringhurst’s ideal). Paragraphs, lists, headings.', 11);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('radius', 'radius-none', '0', 'Tables, rules, page.', 12);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('radius', 'radius-box', '6px', 'The seven boxes.', 13);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('radius', 'radius-node', '8px', 'Diagram nodes.', 14);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('radius', 'radius-pill', '999px', 'Bloom and activity tags.', 15);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('stroke', 'stroke-hair', '1px', 'Table row rules, box frames and header dividers, running-header underline.', 16);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('stroke', 'stroke-strong', '2px', 'Table header rule, table top/bottom rules, diagram connectors, focus ring.', 17);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('stroke', 'stroke-ribbon', '1.33px', 'Cover ribbon rules (1pt, source).', 18);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('stroke', 'stroke-accent', '4px', 'Top rule of in-text boxes (Importante, Error Frecuente, En el aula).', 19);
INSERT INTO dimension_token (family, name, value, usage, position) VALUES ('shadow', 'shadow-page', '{"light":"0 1px 3px rgba(31, 56, 100, 0.12)","dark":"0 1px 3px rgba(0, 0, 0, 0.5)"}', 'Page sheet on the `surface` backdrop (screen only).', 20);
INSERT INTO font_family (key, stack) VALUES ('serif', 'Cambria, Caladea, Georgia, "Times New Roman", serif');
INSERT INTO font_family (key, stack) VALUES ('sans', 'Calibri, Carlito, "Segoe UI", Arial, sans-serif');
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('cover-kicker', 'Cover', 'sans', '14px', '1.3', 700, NULL, '0.08em', 'MANUAL DE FORMACIÓN DOCENTE', '`azure`, centred, upper case.', 0);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('cover-title', 'Cover', 'sans', '40px', '1.1', 700, NULL, NULL, 'Didáctica de la Educación Superior', '`navy`, centred.', 1);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('cover-subtitle', 'Cover', 'serif', '19px', '1.35', 400, 'italic', NULL, 'Fundamentos, estrategias y evaluación para la docencia universitaria', '`ink`, centred.', 2);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('cover-lede', 'Cover', 'serif', '16px', '1.5', 400, NULL, NULL, 'Con desarrollos de didáctica general y de las didácticas específicas', '`ink-muted`, centred.', 3);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('ribbon', 'Cover', 'sans', '14px', '1.6', 400, NULL, NULL, 'Material de estudio para la formación del profesorado universitario', '`navy`, between two 1.33px `navy` rules.', 4);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('cover-meta', 'Cover', 'serif', '14px', '1.5', 400, NULL, NULL, 'Citación: APA 7.ª edición', '`ink-muted`, centred metadata.', 5);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('chapter-kicker', 'Headings', 'sans', '14px', '1.3', 700, NULL, '0.08em', 'UNIDAD 2', 'Chapter number above the unit title, `azure`, upper case.', 6);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('h1', 'Headings', 'sans', '28px', '1.15', 700, NULL, NULL, 'Teorías del aprendizaje en la educación superior', 'Unit title, `navy`; `space-6` before, `space-4` after.', 7);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('h2', 'Headings', 'sans', '23px', '1.25', 700, NULL, NULL, '2.2. La perspectiva sociocultural', 'Numbered section, `azure`; `space-6` before, `space-3` after.', 8);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('h3', 'Headings', 'sans', '19px', '1.3', 700, NULL, NULL, 'Implicancias para la enseñanza', 'Sub-section, `ink` (not azure, so it reads apart from h2); `space-5` before, `space-2` after.', 9);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('toc-title', 'Headings', 'sans', '23px', '1.2', 700, NULL, NULL, 'Índice', '`navy`.', 10);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('body', 'Reading', 'serif', '16px', '1.6', 400, NULL, NULL, 'Vygotsky (1978, p. xx) desplazó el foco desde el individuo hacia la matriz social del aprendizaje.', 'Default paragraph, `ink`, at most `measure-text` wide; left-aligned on screen, justified in print; `space-3` after.', 11);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('lead', 'Reading', 'serif', '19px', '1.55', 400, NULL, NULL, 'Toda decisión de enseñanza descansa en una teoría acerca de cómo aprenden las personas.', 'Opening paragraph of a unit under the title, `ink`.', 12);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('list-item', 'Reading', 'serif', '16px', '1.55', 400, NULL, NULL, 'Diseñar una propuesta de enseñanza alineada.', 'List items; `space-2` after.', 13);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('box-body', 'Reading', 'serif', '16px', '1.55', 400, NULL, NULL, 'Franja entre el nivel de desarrollo real y el potencial.', 'Text inside every box.', 14);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('blockquote', 'Reading', 'serif', '16px', '1.6', 400, NULL, NULL, 'La buena enseñanza es aquella que…', 'APA-7 block quotation (40 words or more): indented `indent-hang`, no quotation marks, citation after the final period.', 15);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('glossary', 'Reading', 'serif', '16px', '1.55', 400, NULL, NULL, 'Andamiaje: Apoyo temporal que ofrece el docente…', 'Glossary entry; the term bold `navy`.', 16);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('reference', 'Reading', 'serif', '14px', '1.55', 400, NULL, NULL, 'Bain, K. (2004). What the best college teachers do. Harvard University Press.', 'APA-7 reference with a French (hanging) indent `indent-hang`; titles italic.', 17);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('table-cell', 'Reading', 'serif', '14px', '1.45', 400, NULL, NULL, 'Construcción activa sobre ideas previas', 'Table body cells.', 18);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('table-title', 'Reading', 'serif', '16px', '1.4', 400, 'italic', NULL, 'Teorías del aprendizaje e implicancias didácticas', 'APA-7 table/figure title, italic, on the line under “Tabla N” / “Figura N”.', 19);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('note', 'Reading', 'serif', '14px', '1.5', 400, NULL, NULL, 'Nota. Elaboración propia a partir de Ausubel (1968, p. xx).', 'APA-7 table/figure note (“Nota.” in italic), `ink-muted`.', 20);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('box-title', 'Labels', 'sans', '14px', '1.2', 700, NULL, '0.06em', 'PUNTOS CLAVE', 'Box title next to its icon, upper case, in the box''s `*-accent`.', 21);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('tag', 'Labels', 'sans', '12px', '1.2', 700, NULL, '0.04em', 'ANALIZAR', 'Bloom level and activity-type tags, upper case.', 22);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('table-number', 'Labels', 'sans', '16px', '1.4', 700, NULL, NULL, 'Tabla 2', 'APA-7 table/figure number, bold, above the title.', 23);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('table-head', 'Labels', 'sans', '14px', '1.3', 700, NULL, NULL, 'Implicancia para enseñar', '`on-table-head` on `table-head`.', 24);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('diagram-label', 'Labels', 'sans', '14px', '1.3', 400, NULL, NULL, 'Andamiaje', 'Diagram node text.', 25);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('diagram-title', 'Labels', 'sans', '16px', '1.25', 700, NULL, NULL, 'Aprendizaje', 'Central node and step titles in diagrams.', 26);
INSERT INTO type_style (name, type_group, family, font_size, line_height, font_weight, font_style, letter_spacing, sample, usage, position) VALUES ('running', 'Labels', 'sans', '12px', '1.3', 400, NULL, NULL, 'Didáctica de la Educación Superior', 'Running header and “Página N” footer, `running`.', 27);
INSERT INTO component (name, comp_group, summary, position) VALUES ('Page', 'Layout', 'A manual page: paper sheet, margins, running header and “Página N” footer.', 0);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Page', 'header', 'string', 0, 'Running-header text.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Page', 'page', 'number', 0, 'Footer page number.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Page', 'children', 'ReactNode', 1, 'Page content.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('TitlePage', 'Layout', 'The manual''s cover: kicker, title, italic subtitle, lede, ribbon and metadata lines, all centred.', 1);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('TitlePage', 'kicker', 'string', 0, 'Series line, upper case.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('TitlePage', 'title', 'string', 1, 'Book title.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('TitlePage', 'subtitle', 'string', 0, 'Italic subtitle.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('TitlePage', 'lede', 'string', 0, 'Scope line.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('TitlePage', 'ribbon', 'string', 0, 'Text between the two navy rules.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('TitlePage', 'meta', 'string[]', 0, 'Metadata lines.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('TableOfContents', 'Layout', '“Índice”: levels 1–3 with dotted leaders to the page number.', 2);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('TableOfContents', 'title', 'string', 0, 'Defaults to “Índice”.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('TableOfContents', 'entries', '{ title; page; level? }[]', 1, 'TOC lines in reading order.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('ChapterOpener', 'Layout', 'Unit opener: “Unidad N” kicker, unit title (h1) and a lead paragraph.', 3);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('ChapterOpener', 'number', 'number', 0, 'Unit number.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('ChapterOpener', 'title', 'string', 1, 'Unit title, without “Unidad N.”.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('ChapterOpener', 'lead', 'ReactNode', 0, 'Opening paragraph.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('ChapterOpener', 'id', 'string', 0, 'Anchor id.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('BoxLegend', 'Layout', '“Cómo usar este manual”: the legend of box types, grouped by family.', 4);
INSERT INTO component (name, comp_group, summary, position) VALUES ('Heading', 'Text', 'Headings: 1 for unnumbered unit-level sections (Glosario, Referencias), 2 sections, 3 sub-sections.', 5);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Heading', 'level', '1 | 2 | 3', 0, 'Defaults to 2.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Heading', 'id', 'string', 0, 'Anchor id.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Heading', 'children', 'ReactNode', 1, 'Heading text, numbered “2.1. …”.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('Paragraph', 'Text', 'Body paragraph: 16px Cambria, 1.6 leading; left-aligned on screen, justified in print.', 6);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Paragraph', 'children', 'ReactNode', 1, 'Text with <Cite> citations.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('BulletList', 'Text', 'Bullet list (● ○ ■ by level). An item is a string or { text, items } for a nested level.', 7);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('BulletList', 'items', '(string | { text; items? })[]', 1, 'List items.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('Cite', 'Citations', 'APA 7 in-text citation with page: (Biggs & Tang, 2011, p. 45) or Biggs y Tang (2011, p. 45).', 8);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Cite', 'authors', 'string[]', 1, 'Surnames in source order; 3+ become “et al.”.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Cite', 'year', 'number | string', 1, 'Year, or “s. f.”.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Cite', 'page', 'number | string', 1, 'Page or range (“45–47” → pp.).');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Cite', 'locator', 'string', 0, 'Overrides page: “párr. 4”, “cap. 3”.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Cite', 'narrative', 'boolean', 0, 'Narrative form with “y”.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Cite', 'works', 'Work[]', 0, 'Several works in one parenthesis, alphabetical.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('Quote', 'Citations', 'Short quotation (under 40 words) in English double quotes “…”, followed by its APA citation.', 9);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Quote', 'children', 'ReactNode', 1, 'Quoted words, verbatim.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Quote', 'cite', '{ authors; year; page }', 1, 'Source with page.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('BlockQuote', 'Citations', 'APA 7 block quotation (40 words or more): indented, no quotation marks, citation after the final period.', 10);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('BlockQuote', 'children', 'ReactNode', 1, 'Quoted passage ending with its period.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('BlockQuote', 'cite', '{ authors; year; page }', 1, 'Source with page.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('KeyPoints', 'Boxes', '“Puntos Clave”: the unit summary, first box of every unit (3–5 one-line items), with optional “Antes de leer” questions.', 11);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('KeyPoints', 'items', 'ReactNode[]', 1, '3–6 key points, one sentence each.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('KeyPoints', 'before', 'ReactNode[]', 0, '1–3 “Antes de leer” questions, revisited in “Para Seguir Pensando”.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('KeyPoints', 'title', 'string', 0, 'Overrides “Puntos Clave”.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('Objectives', 'Boxes', '“Objetivos”: numbered learning objectives (O1, O2…), each tagged with its Bloom (revised) level.', 12);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Objectives', 'items', '{ id?: string; level: BloomId; text }[]', 1, 'Objectives starting with a verb of their level; ids default to O1, O2…');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Objectives', 'intro', 'string', 0, 'Lead-in line.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Objectives', 'title', 'string', 0, 'Overrides “Objetivos”.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('Important', 'Boxes', '“Importante”: a key concept or definition the reader should retain.', 13);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Important', 'term', 'string', 0, 'The concept defined.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Important', 'children', 'ReactNode', 1, 'Definition with its citation.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Important', 'title', 'string', 0, 'Overrides “Importante”.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('CommonMistake', 'Boxes', '“Error Frecuente”: a refutation in three moves — misconception, cited correction, and why the belief does not hold.', 14);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('CommonMistake', 'misconception', 'ReactNode', 1, 'The belief, stated plainly.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('CommonMistake', 'correction', 'ReactNode', 1, 'What the evidence shows, cited.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('CommonMistake', 'explanation', 'ReactNode', 0, 'Why the belief is wrong or why it is attractive (“Por qué no se sostiene”).');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('CommonMistake', 'children', 'ReactNode', 0, 'Optional teaching note.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('CommonMistake', 'title', 'string', 0, 'Overrides “Error Frecuente”.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('Classroom', 'Boxes', '“En el Aula”: a worked classroom case — situation, didactic decision and its rationale.', 15);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Classroom', 'discipline', '''sociales''|''salud''|''general''|string', 0, 'Discipline tag in the header.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Classroom', 'situation', 'ReactNode', 1, 'The classroom situation, concrete.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Classroom', 'decision', 'ReactNode', 1, 'What the teacher does.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Classroom', 'rationale', 'ReactNode', 0, 'Why, with its citation.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Classroom', 'title', 'string', 0, 'Overrides “En el Aula”.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('ThinkFurther', 'Boxes', '“Para Seguir Pensando”: open questions with no single answer; not assessed.', 16);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('ThinkFurther', 'questions', 'ReactNode[]', 1, '2–5 open questions.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('ThinkFurther', 'title', 'string', 0, 'Overrides “Para Seguir Pensando”.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('SelfCheck', 'Boxes', '“Autoevaluación”: retrieval practice with feedback; answers open on screen and print as a key.', 17);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('SelfCheck', 'items', '{ question; answer; review?: string }[]', 1, '3–5 short recall questions; review names an earlier unit.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('SelfCheck', 'title', 'string', 0, 'Overrides “Autoevaluación”.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('Activities', 'Boxes', '“Actividades”: assessable questions and tasks, tagged with type, Bloom level and the objectives they practise.', 18);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Activities', 'items', '(string | { type?; level?: BloomId; objectives?: string[]; text })[]', 1, 'Numbered activities; objectives link to O1, O2…');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Activities', 'title', 'string', 0, 'Overrides “Actividades”.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('ReferencesBox', 'Boxes', '“Referencias”: the unit''s APA 7 reference list, French (hanging) indent. Children: <Reference> items.', 19);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('ReferencesBox', 'children', 'ReactNode', 1, '<Reference> items, alphabetical.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('ReferencesBox', 'title', 'string', 0, 'Overrides “Referencias”.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('AlignmentTable', 'Boxes', 'Alignment table: which activities practise each objective, flagging gaps and level mismatches.', 20);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('AlignmentTable', 'objectives', 'Objective[]', 1, 'The same array passed to Objectives.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('AlignmentTable', 'activities', 'Activity[]', 1, 'The same array passed to Activities.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('AlignmentTable', 'title', 'string', 0, 'Defaults to “Alineamiento de la unidad”.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('Box', 'Boxes', 'The shared frame of the didactic boxes; its family sets the shape (open: filled header, text: top rule, close: plain frame).', 21);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Box', 'kind', '''keypoints''|''objectives''|''important''|''mistake''|''example''|''thinking''|''selfcheck''|''activities''|''references''', 1, 'Box type.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Box', 'title', 'string', 0, 'Overrides the type''s title.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Box', 'children', 'ReactNode', 1, 'Body.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('Icon', 'Boxes', 'A Lucide line icon drawn in currentColor. Decorative unless given a label.', 22);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Icon', 'name', 'string', 1, 'One of the seven box icons.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Icon', 'size', 'number', 0, 'Pixels, default 20.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Icon', 'label', 'string', 0, 'Accessible name; omit when decorative.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('DataTable', 'Tables and figures', 'APA 7 table: “Tabla N” and italic title above, horizontal rules, light header (or `filled`), optional row headers, “Nota.” below.', 23);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('DataTable', 'columns', 'string[]', 1, 'Header labels.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('DataTable', 'rows', 'ReactNode[][]', 1, 'Body rows.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('DataTable', 'widths', 'string[]', 0, 'Column widths.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('DataTable', 'number', 'number', 0, 'Table number.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('DataTable', 'id', 'string', 0, 'Registry id inside <Numbering> (automatic number, cross-reference target).');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('DataTable', 'title', 'string', 0, 'Italic title.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('DataTable', 'note', 'ReactNode', 0, 'Note text after “Nota.”.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('DataTable', 'rowHeader', 'boolean', 0, 'First column as row headers (conceptual tables).');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('DataTable', 'filled', 'boolean', 0, 'Solid navy header bar (slides, posters).');
INSERT INTO component (name, comp_group, summary, position) VALUES ('Figure', 'Tables and figures', 'APA 7 figure: “Figura N” and the italic title above a diagram or image; “Nota.” below. Numbered automatically by id inside <Numbering>.', 24);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Figure', 'number', 'number', 0, 'Figure number.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Figure', 'id', 'string', 0, 'Registry id inside <Numbering>: the number comes from it and <FigRef> can point to it.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Figure', 'title', 'string', 0, 'Italic title.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Figure', 'note', 'ReactNode', 0, 'Note text.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Figure', 'children', 'ReactNode', 1, 'A diagram or image.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('Numbering', 'Tables and figures', 'Numbers figures and tables from their ids, in order of first mention, so cross-references never break.', 25);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Numbering', 'figures', 'string[]', 0, 'Figure ids in order of first mention.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Numbering', 'tables', 'string[]', 0, 'Table ids in order of first mention.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Numbering', 'firstFigure', 'number', 0, 'Start of the figure count (continue from an earlier unit).');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Numbering', 'firstTable', 'number', 0, 'Start of the table count.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Numbering', 'children', 'ReactNode', 1, 'The unit.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('FigRef', 'Tables and figures', 'Cross-reference to a figure or table by id: “Figura 2”, or with paren “(véase la Figura 2)”.', 26);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('FigRef', 'to', 'string', 1, 'Figure or table id.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('FigRef', 'paren', 'boolean', 0, 'Parenthetical form “(véase la …)”.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('ConceptWeb', 'Diagrams', 'Concept web: a central concept linked to up to 8 related concepts, with relation labels and short details.', 27);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('ConceptWeb', 'center', 'string', 1, 'Central concept.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('ConceptWeb', 'nodes', '{ label; relation?; detail? }[]', 1, 'Related concepts, clockwise from the top.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('ConceptWeb', 'label', 'string', 0, 'Accessible description.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('CycleDiagram', 'Diagrams', 'Cycle: 3–8 steps around a circle joined by arrows, with an optional centre label.', 28);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('CycleDiagram', 'steps', '{ title; text? }[]', 1, 'Steps clockwise from the top.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('CycleDiagram', 'center', 'string', 0, 'Centre label.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('CycleDiagram', 'label', 'string', 0, 'Accessible description.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('Pyramid', 'Diagrams', 'Pyramid of levels, top (most advanced) first, e.g. Miller''s pyramid; descriptions to the right.', 29);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Pyramid', 'levels', '{ title; text? }[]', 1, 'Levels from apex to base (2–6).');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Pyramid', 'label', 'string', 0, 'Accessible description.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('ProcessFlow', 'Diagrams', 'Process flow: numbered steps joined by arrows; horizontal on wide screens, vertical on narrow ones.', 30);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('ProcessFlow', 'steps', '{ title; text? }[]', 1, '2–5 steps in order.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('ProcessFlow', 'label', 'string', 0, 'Accessible name of the list.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('GlossaryEntry', 'Reference', 'Glossary entry: the term in bold navy, a colon, then the definition.', 31);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('GlossaryEntry', 'term', 'string', 1, 'Term, without the colon.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('GlossaryEntry', 'id', 'string', 0, 'Link target for <Term to>.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('GlossaryEntry', 'children', 'ReactNode', 1, 'Definition.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('Reference', 'Reference', 'One APA 7 reference with a French (hanging) indent; pass the title in <i>.', 32);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Reference', 'children', 'ReactNode', 1, 'The reference, italics marked with <i>.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('Term', 'Reference', 'A term in running text linked to its glossary entry (dotted azure underline).', 33);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Term', 'to', 'string', 1, 'Glossary entry id.');
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Term', 'children', 'ReactNode', 1, 'The term as it appears in the sentence.');
INSERT INTO component (name, comp_group, summary, position) VALUES ('Glossary', 'Reference', 'Glossary built from entries, sorted alphabetically (Spanish collation); each entry is a link target for <Term>.', 34);
INSERT INTO component_prop (component, name, type, required, description) VALUES ('Glossary', 'entries', '{ id; term; definition }[]', 1, 'Entries in any order.');
INSERT INTO box_type (kind, family, title, component, icon, placement, icon_svg, position) VALUES ('keypoints', 'open', 'Puntos Clave', 'KeyPoints', 'key-round', 'Opens each unit, right after the unit title and lead.', '<!-- Lucide “key-round” v0.460.0, ISC licence. Ink: #1f3864 (keypoints-accent, light theme). -->
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="#1f3864"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M2.586 17.414A2 2 0 0 0 2 18.828V21a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h1a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h.172a2 2 0 0 0 1.414-.586l.814-.814a6.5 6.5 0 1 0-4-4z" />
  <circle cx="16.5" cy="7.5" r=".5" fill="currentColor" />
</svg>
', 0);
INSERT INTO box_type (kind, family, title, component, icon, placement, icon_svg, position) VALUES ('objectives', 'open', 'Objetivos', 'Objectives', 'target', 'Right after “Puntos Clave”.', '<!-- Lucide “target” v0.460.0, ISC licence. Ink: #0d5c63 (objectives-accent, light theme). -->
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="#0d5c63"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <circle cx="12" cy="12" r="10" />
  <circle cx="12" cy="12" r="6" />
  <circle cx="12" cy="12" r="2" />
</svg>
', 1);
INSERT INTO box_type (kind, family, title, component, icon, placement, icon_svg, position) VALUES ('important', 'text', 'Importante', 'Important', 'star', 'In the text, for a key concept or definition.', '<!-- Lucide “star” v0.460.0, ISC licence. Ink: #8a4b00 (important-accent, light theme). -->
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="#8a4b00"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z" />
</svg>
', 2);
INSERT INTO box_type (kind, family, title, component, icon, placement, icon_svg, position) VALUES ('mistake', 'text', 'Error Frecuente', 'CommonMistake', 'triangle-alert', 'In the text, next to the idea it corrects.', '<!-- Lucide “triangle-alert” v0.460.0, ISC licence. Ink: #a3271c (mistake-accent, light theme). -->
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="#a3271c"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3" />
  <path d="M12 9v4" />
  <path d="M12 17h.01" />
</svg>
', 3);
INSERT INTO box_type (kind, family, title, component, icon, placement, icon_svg, position) VALUES ('example', 'text', 'En el Aula', 'Classroom', 'school', 'In the text, after the concept it applies.', '<!-- Lucide “school” v0.460.0, ISC licence. Ink: #8b2f62 (example-accent, light theme). -->
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="#8b2f62"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M14 22v-4a2 2 0 1 0-4 0v4" />
  <path d="m18 10 3.447 1.724a1 1 0 0 1 .553.894V20a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-7.382a1 1 0 0 1 .553-.894L6 10" />
  <path d="M18 5v17" />
  <path d="m4 6 7.106-3.553a2 2 0 0 1 1.788 0L20 6" />
  <path d="M6 5v17" />
  <circle cx="12" cy="9" r="2" />
</svg>
', 4);
INSERT INTO box_type (kind, family, title, component, icon, placement, icon_svg, position) VALUES ('thinking', 'close', 'Para Seguir Pensando', 'ThinkFurther', 'message-circle-question', 'Closing sequence, first.', '<!-- Lucide “message-circle-question” v0.460.0, ISC licence. Ink: #5a3486 (thinking-accent, light theme). -->
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="#5a3486"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" />
  <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />
  <path d="M12 17h.01" />
</svg>
', 5);
INSERT INTO box_type (kind, family, title, component, icon, placement, icon_svg, position) VALUES ('selfcheck', 'close', 'Autoevaluación', 'SelfCheck', 'list-checks', 'Closing sequence, after “Para Seguir Pensando”.', '<!-- Lucide “list-checks” v0.460.0, ISC licence. Ink: #0f5f86 (selfcheck-accent, light theme). -->
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="#0f5f86"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="m3 17 2 2 4-4" />
  <path d="m3 7 2 2 4-4" />
  <path d="M13 6h8" />
  <path d="M13 12h8" />
  <path d="M13 18h8" />
</svg>
', 6);
INSERT INTO box_type (kind, family, title, component, icon, placement, icon_svg, position) VALUES ('activities', 'close', 'Actividades', 'Activities', 'pencil-line', 'Closing sequence, after “Autoevaluación”, followed by the alignment table.', '<!-- Lucide “pencil-line” v0.460.0, ISC licence. Ink: #2d6a2e (activities-accent, light theme). -->
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="#2d6a2e"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M12 20h9" />
  <path d="M16.376 3.622a1 1 0 0 1 3.002 3.002L7.368 18.635a2 2 0 0 1-.855.506l-2.872.838a.5.5 0 0 1-.62-.62l.838-2.872a2 2 0 0 1 .506-.854z" />
  <path d="m15 5 3 3" />
</svg>
', 7);
INSERT INTO box_type (kind, family, title, component, icon, placement, icon_svg, position) VALUES ('references', 'close', 'Referencias', 'ReferencesBox', 'book-open-text', 'Closes each unit.', '<!-- Lucide “book-open-text” v0.460.0, ISC licence. Ink: #3f4b5e (references-accent, light theme). -->
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="#3f4b5e"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M12 7v14" />
  <path d="M16 12h2" />
  <path d="M16 8h2" />
  <path d="M3 18a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h5a4 4 0 0 1 4 4 4 4 0 0 1 4-4h5a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-6a3 3 0 0 0-3 3 3 3 0 0 0-3-3z" />
  <path d="M6 12h2" />
  <path d="M6 8h2" />
</svg>
', 8);
INSERT INTO bloom_level (id, level, name, verbs) VALUES ('recordar', 1, 'Recordar', 'definir, enumerar, identificar, nombrar, reconocer, recuperar');
INSERT INTO bloom_level (id, level, name, verbs) VALUES ('comprender', 2, 'Comprender', 'explicar, describir, clasificar, resumir, ejemplificar, interpretar');
INSERT INTO bloom_level (id, level, name, verbs) VALUES ('aplicar', 3, 'Aplicar', 'aplicar, utilizar, resolver, implementar, ejecutar, demostrar');
INSERT INTO bloom_level (id, level, name, verbs) VALUES ('analizar', 4, 'Analizar', 'analizar, comparar, distinguir, organizar, diferenciar, relacionar');
INSERT INTO bloom_level (id, level, name, verbs) VALUES ('evaluar', 5, 'Evaluar', 'evaluar, juzgar, fundamentar, valorar, argumentar, criticar');
INSERT INTO bloom_level (id, level, name, verbs) VALUES ('crear', 6, 'Crear', 'diseñar, elaborar, planificar, producir, construir, formular');
COMMIT;
