// tokens/tokens.json + src/components.meta.json → db/design-system.sqlite and db/seed.sql.
import { DatabaseSync } from 'node:sqlite';
import { readFileSync, writeFileSync, rmSync } from 'node:fs';

const read = (p) => readFileSync(new URL(`../${p}`, import.meta.url), 'utf8');
const t = JSON.parse(read('tokens/tokens.json'));
const comps = JSON.parse(read('src/components.meta.json'));
const boxes = JSON.parse(read('src/boxes.config.json'));
const { BLOOM } = await import('../src/bloom.js');
const dbFile = new URL('../db/design-system.sqlite', import.meta.url);
rmSync(dbFile, { force: true });

const stmts = [];
const q = (v) => (v == null ? 'NULL' : typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const insert = (table, row) =>
  stmts.push(`INSERT INTO ${table} (${Object.keys(row).join(', ')}) VALUES (${Object.values(row).map(q).join(', ')});`);

insert('system', { key: 'name', value: t.name });
insert('system', { key: 'version', value: String(t.version) });
insert('system', { key: 'source', value: t.meta?.source ?? '' });

const themes = t.color.themes.map((th) => th.id);
t.color.themes.forEach((th, i) => insert('theme', { id: th.id, name: th.name, position: i }));
t.color.tokens.forEach((c, i) => {
  insert('color_token', { name: c.name, usage: c.usage, position: i });
  for (const th of themes) {
    const v = typeof c.value === 'string' ? c.value : c.value[th] ?? c.value[themes[0]];
    insert('color_value', { token: c.name, theme: th, value: v });
  }
});

let pos = 0;
for (const [family, fam] of Object.entries(t)) {
  if (['name', 'version', 'meta', 'color', 'type'].includes(family) || !fam?.tokens) continue;
  for (const tok of fam.tokens)
    insert('dimension_token', { family, name: tok.name, value: typeof tok.value === 'object' ? JSON.stringify(tok.value) : tok.value, usage: tok.usage, position: pos++ });
}

for (const [key, stack] of Object.entries(t.type.families)) insert('font_family', { key, stack });
pos = 0;
for (const g of t.type.groups) {
  for (const s of g.styles) {
    insert('type_style', {
      name: s.name, type_group: g.name, family: s.family || g.family, font_size: s.fontSize,
      line_height: s.lineHeight != null ? String(s.lineHeight) : null, font_weight: s.fontWeight ?? null,
      font_style: s.fontStyle ?? null, letter_spacing: s.letterSpacing ?? null, sample: s.sample ?? null,
      usage: s.usage ?? null, position: pos++,
    });
  }
}

comps.forEach((c, i) => {
  insert('component', { name: c.name, comp_group: c.group, summary: c.summary, position: i });
  for (const [name, type, required, description] of c.props)
    insert('component_prop', { component: c.name, name, type, required: required ? 1 : 0, description });
});

boxes.forEach((b, i) =>
  insert('box_type', {
    kind: b.kind, title: b.title, component: b.component, icon: b.icon, placement: b.placement,
    icon_svg: read(`icons/${b.kind}-${b.icon}.svg`), position: i,
  })
);
for (const b of BLOOM) insert('bloom_level', { id: b.id, level: b.level, name: b.name, verbs: b.verbs.join(', ') });

const seed = `-- Generated by scripts/build-db.mjs from tokens/tokens.json and src/components.meta.json.\nBEGIN;\n${stmts.join('\n')}\nCOMMIT;\n`;
writeFileSync(new URL('../db/seed.sql', import.meta.url), seed);

const db = new DatabaseSync(dbFile.pathname);
db.exec('PRAGMA foreign_keys = ON;');
db.exec(read('db/schema.sql'));
db.exec(seed);
const count = (tbl) => db.prepare(`SELECT COUNT(*) AS n FROM ${tbl}`).get().n;
console.log(
  `db/design-system.sqlite: ${count('color_token')} colours × ${count('theme')} themes, ` +
    `${count('type_style')} type styles, ${count('dimension_token')} dimensions, ${count('component')} components, ` +
    `${count('box_type')} box types, ${count('bloom_level')} Bloom levels`
);
db.close();
