// Renders src/examples/chapter.jsx to static HTML: html/index.html is the
// plain HTML/CSS version of the system (no JavaScript at all).
import { build } from 'esbuild';
import { writeFileSync, rmSync } from 'node:fs';

const tmp = new URL('../dist/.render-demo.mjs', import.meta.url);
await build({
  stdin: {
    contents: `
      import React from 'react';
      import { renderToStaticMarkup } from 'react-dom/server';
      import { Page, TitlePage } from '../src/index.js';
      import { ChapterExample, DiagramsExample, LegendExample } from '../src/examples/chapter.jsx';
      const h = React.createElement;
      export const cover = renderToStaticMarkup(h(Page, null, h(TitlePage, {
        kicker: 'Manual de formación docente', title: 'Didáctica de la Educación Superior',
        subtitle: 'Fundamentos, estrategias y evaluación para la docencia universitaria',
        lede: 'Con desarrollos de didáctica general y de las didácticas específicas de las ciencias sociales y de las ciencias de la salud',
        ribbon: 'Material de estudio para la formación del profesorado universitario',
        meta: ['Nivel: graduados universitarios en formación pedagógica', 'Citación: APA 7.ª edición', 'Año 2026'] })));
      export const legend = renderToStaticMarkup(h(Page, { header: 'Didáctica de la Educación Superior', page: 3 }, h(LegendExample)));
      export const chapter = renderToStaticMarkup(h(Page, { header: 'Didáctica de la Educación Superior', page: 12 }, h(ChapterExample)));
      export const diagrams = renderToStaticMarkup(h(Page, { header: 'Didáctica de la Educación Superior', page: 13 }, h(DiagramsExample)));
    `,
    resolveDir: new URL('../src', import.meta.url).pathname,
    loader: 'jsx',
  },
  bundle: true, platform: 'node', format: 'esm', jsx: 'transform', loader: { '.jsx': 'jsx' }, packages: 'external',
  outfile: tmp.pathname, logLevel: 'warning',
});
const { cover, legend, chapter, diagrams } = await import(`${tmp.href}?t=${Date.now()}`);
rmSync(tmp);

const html = `<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Didáctica Universitaria — HTML/CSS</title>
  <link rel="stylesheet" href="../dist/tokens.css">
  <link rel="stylesheet" href="../dist/didactica.css">
  <style>
    body { margin: 0; background: var(--surface); padding: var(--space-5) var(--space-3); }
    .du-page + .du-page { margin-top: var(--space-5); }
    .theme-toggle { position: fixed; top: 12px; right: 12px; font: inherit; }
  </style>
</head>
<body>
  <!-- Generated by scripts/build-demo.mjs from src/examples/chapter.jsx: the same markup the React components render, with no JavaScript. -->
  <button class="theme-toggle running" type="button" onclick="var r=document.documentElement;r.dataset.theme=(r.dataset.theme||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'))==='dark'?'light':'dark'">Tema claro / oscuro</button>
  ${cover}
  ${legend}
  ${chapter}
  ${diagrams}
</body>
</html>
`;
writeFileSync(new URL('../html/index.html', import.meta.url), html);
console.log('html/index.html written');
