// Lucide (ISC) icons for the seven boxes → src/icons.generated.js (React element
// trees, stroke = currentColor) and icons/<name>.svg (single-ink copies in the
// box's light-theme accent, for <img> use and the design-system asset group).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const root = new URL('..', import.meta.url);
const boxes = JSON.parse(readFileSync(new URL('src/boxes.config.json', root), 'utf8'));
const tokens = JSON.parse(readFileSync(new URL('tokens/tokens.json', root), 'utf8'));
const color = Object.fromEntries(tokens.color.tokens.map((t) => [t.name, t.value]));
const LUCIDE = new URL('node_modules/lucide-static/icons/', root);

const parse = (svg) => {
  const body = svg.replace(/<!--[\s\S]*?-->/g, '').replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>[\s\S]*$/, '');
  return [...body.matchAll(/<(\w+)\s+([^>]*?)\/?>/g)].map(([, tag, attrs]) => [
    tag,
    Object.fromEntries([...attrs.matchAll(/([\w-]+)="([^"]*)"/g)].map(([, k, v]) => [k, v])),
  ]);
};

const icons = {};
mkdirSync(new URL('icons/', root), { recursive: true });
for (const b of boxes) {
  const src = readFileSync(new URL(`${b.icon}.svg`, LUCIDE), 'utf8');
  icons[b.icon] = parse(src);
  const ink = color[`${b.kind}-accent`].light;
  const out = src
    .replace(/<!--[\s\S]*?-->\s*/, `<!-- Lucide “${b.icon}” v0.460.0, ISC licence. Ink: ${ink} (${b.kind}-accent, light theme). -->\n`)
    .replace(/class="[^"]*"\s*/, '')
    .replace('stroke="currentColor"', `stroke="${ink}"`);
  writeFileSync(new URL(`icons/${b.kind}-${b.icon}.svg`, root), out);
}
writeFileSync(
  new URL('src/icons.generated.js', root),
  `// Generated by scripts/build-icons.mjs from lucide-static@0.460.0 (ISC licence). Do not edit.\nexport const ICONS = ${JSON.stringify(icons, null, 2)};\n`
);
console.log(`icons: ${Object.keys(icons).join(', ')}`);
